const livros = [
    {
        id:1,
        nome:"Rangers: Ordem dos Arqueiros 1 Ruínas de Gorlan",
        autor:"John Flanagan",
        categoria:"Fantasia",
        paginas:288,
        recomenda:true,
        leu:true,
    },
    {
        id:2,
        nome:"Rangers: Ordem dos Arqueiros 2 Ponte em chamas",
        autor:"John Flanagan",
        categoria:"Aventura",
        paginas:289,
        recomenda:false,
        leu:true,
    },
    {
        id:3,
        nome:"Rangers: Ordem dos Arqueiros 3 Terra do Gelo",
        autor:"John Flanagan",
        categoria:"Fantasia",
        paginas:290,
        recomenda:true,
        leu:true,
    },
    {
        id:4,
        nome:"Rangers: Ordem dos Arqueiros 4 Folha de Carvalho",
        autor:"John Flanagan",
        categoria:"Aventura",
        paginas:291,
        recomenda:true,
        leu:true,
    },
    {
        id:5,
        nome:"Rangers: Ordem dos Arqueiros 5 Feiticeiro do Norte",
        autor:"John Flanagan",
        categoria:"Fantasia",
        paginas:292,
        recomenda:true,
        leu:true,
    },
    {
        id:6,
        nome:"Rangers: Ordem dos Arqueiros 6 Cerco à Macindaw",
        autor:"John Flanagan",
        categoria:"Aventura",
        paginas:293,
        recomenda:true,
        leu:true,
    },
    {
        id:7,
        nome:"Rangers: Ordem dos Arqueiros 7 Resgate de Erak",
        autor:"John Flanagan",
        categoria:"Fantasia",
        paginas:294,
        recomenda:true,
        leu:true,
    },
    {
        id:8,
        nome:"Rangers: Ordem dos Arqueiros 8 Reis de Clonmel",
        autor:"John Flanagan",
        categoria:"Aventura",
        paginas:295,
        recomenda:true,
        leu:true,
    },
    {
        id:9,
        nome:"Rangers: Ordem dos Arqueiros 9 Halt em Perigo",
        autor:"John Flanagan",
        categoria:"Fantasia",
        paginas:296,
        recomenda:true,
        leu:true,
    },
    {
        id:10,
        nome:"Rangers: Ordem dos Arqueiros 10 Imperador de Nihon-Ja",
        autor:"John Flanagan",
        categoria:"Aventura",
        paginas:297,
        recomenda:true,
        leu:true,
    },
    {
        id:11,
        nome:"Rangers: Ordem dos Arqueiros 11 As historias perdidas",
        autor:"John Flanagan",
        categoria:"Fantasia",
        paginas:298,
        recomenda:false,
        leu:true,
    },
    {
        id:12,
        nome:"Rangers: Ordem dos Arqueiros 12 O Arqueiro do Rei",
        autor:"John Flanagan",
        categoria:"Aventura",
        paginas:299,
        recomenda:false,
        leu:true,
    }

]

module.exports=livros